/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab8;

public class Library {
	public static void main(String args[]) {
		Library lib = new Library();
		if(lib.someLibraryMethod())
		System.out.println("When there is a fire, commit and push."); //add comment
		System.out.println("Change println"); // change comment
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
